"""add_user_tier_and_is_admin

Revision ID: 11d8c9a5e49d
Revises: 6107cfb5fa78
Create Date: 2026-02-20 14:05:29.331489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d8c9a5e49d'
down_revision: Union[str, None] = '6107cfb5fa78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tier', sa.String(length=20), server_default='free', nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'tier')
    # ### end Alembic commands ###
